project_id = "gyovaxenxtrogrxmbjde"

[functions.extract-expense]
verify_jwt = true

[functions.bulk-import-users]
verify_jwt = true

[functions.fetch-exchange-rates]
verify_jwt = true

[functions.review-expense-categories]
verify_jwt = true

[functions.webhook-dispatcher]
verify_jwt = true
